name: CI

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Extract out parent branch
        shell: bash
        run: echo "##[set-output name=parent_branch;]$(git show-branch -a | grep '\*' | grep -v `git rev-parse --abbrev-ref HEAD` | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')"
        id: extract_parent_branch

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn run build

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test